version: "3.7"
services:
    gluetun:
        image: qmcgaw/private-internet-access
        container_name: gluetun
        cap_add:
            - NET_ADMIN
        network_mode: { docker_network_name }
        ports: 
            - 8888:8888/tcp # Tinyproxy
            - 8388:8388/tcp # Shadowsocks
            - 8388:8388/udp # Shadowsocks
            - 8000:8000/tcp # Built-in HTTP control server
            - 9091:9091 # transmission
            - 51413:51413 # transmission
            - 51413:51413/udp # transmission
        environment: 
            - VPNSP=private internet access
            - PROTOCOL=udp
            - OPENVPN_VERBOSITY=1
            - OPENVPN_ROOT=no 
            - REGION= {your PIA region }
            - USER={username}
            - PASSWORD={password}
            - PIA_ENCRYPTION=strong
            - PORT_FORWARDING=on 
        restart: always