version: '2.1'
services:
    reverse_proxy:
        image: linuxserver/nginx
        container_name: reverse_proxy
        depends_on:
            - nginx
            - transmission
        volumes:
            - ./nginx/nginx.conf:/etc/nginx/nginx.conf
        ports:
            - "80:80"
            - "443:443"
    nginx:
        image: linuxserver/nginx
        container_name: nginx
        depends_on:
            - transmission
        environment: 
            - PUID=1000
            - PGID=1000
            - TZ=
        volumes:
            - ./www:/data/www
        ports:
            - "8080:80"
    transmission:
        image: linuxserver/transmission
        container_name: transmission
        network_mode: "container:gluetun"
        environment: 
            - PUID=1000
            - PGID=1000
            - TZ=
            - USER=
            - PASS=
        volumes:
            - /path/to/config:/config 
            - /path/to/downloads:/downloads
            - /path/to/watch:/watch
        restart: on-failure

    